kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mariadb-data
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
